### ISSUE TITLE
Node Modules

### ISSUE THREAD

**Issue by nwhite89** [sirvan3tr/DataBankingReact#1]
Shouldn't contain node_modules folder in a repository add to `.gitginore`

![https://media.giphy.com/media/A2ivvbp54Freo/giphy.gif](https://media.giphy.com/media/A2ivvbp54Freo/giphy.gif)

**Comment by sirvan3tr** [comment]
Do you wana job?

**Comment by nwhite89** [comment]
Can't afford me

**Comment by sirvan3tr** [comment]
soon...
